[versions]
# Build
aesCbc = "0.5.1"
agp = "8.13.2"
cryptoRand = "0.6.0"
ddPlist = "1.28"
encodingBase64 = "1.2.3"
kotlin = "2.3.10"
compose-hot-reload = "1.0.0"
kobweb = "0.24.0"

# Compose
compose = "1.10.0" # BOM for JetBrains Compose libraries
coilCompose = "3.3.0"
composeIcons = "1.1.1"
androidx-activityCompose = "1.12.3"
htmlconverter = "1.1.0"
material3 = "1.9.0"

# AndroidX
compose-multiplatform-lifecycle = "2.10.0-alpha08"

# Kotlin & Coroutines
kotlinx-coroutines = "1.10.2"
kotlinx-collections-immutable = "0.4.0"
kotlinx-serialization = "1.10.0"
kotlinx-datetime = "0.7.1"

# Networking - Ktor
ktor = "3.4.0"

# Dependency Injection - Koin
koin = "4.1.1"

# Database
qrKit = "3.1.3"
room = "2.8.4"
scanner = "0.6.0"
secureRandom = "0.4.0"
slf4jSimple = "2.0.17"
sqlite = "2.6.2"
ksp = "2.3.4"

# Multiplatform Helpers
multiplatformSettings = "1.3.0"
napier = "2.7.1"

# Desktop Specific
jkeymasterVersion = "1.3"
jna = "5.18.1"
jnativehook = "2.2.2"
composenativetray = "1.0.10"
ui = "1.10.0-beta01"
core = "1.17.0"
lifecycleService = "2.10.0"

# Navigation
nav3Core = "1.0.0-alpha06"
lifecycleViewmodelNav3 = "2.10.0"


[libraries]
# Compose
dd-plist = { module = "com.googlecode.plist:dd-plist", version.ref = "ddPlist" }
qr-kit = { module = "network.chaintech:qr-kit", version.ref = "qrKit" }
scanner = { module = "io.github.kalinjul.easyqrscan:scanner", version.ref = "scanner" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }

ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-html = { module = "org.jetbrains.compose.html:html-core", version.ref = "compose" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
kobweb-core = { module = "com.varabyte.kobweb:kobweb-core", version.ref = "kobweb" }
kobweb-silk = { module = "com.varabyte.kobweb:kobweb-silk", version.ref = "kobweb" }

# UI
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
composeIcons-feather = { module = "br.com.devsrsouza.compose.icons:feather", version.ref = "composeIcons" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
htmlconverter = { module = "be.digitalia.compose.htmlconverter:htmlconverter", version.ref = "htmlconverter" }

# AndroidX - Lifecycle
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-multiplatform-lifecycle" }
androidx-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "compose-multiplatform-lifecycle" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

# Kotlinx
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Ktor Client
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-client-winhttp = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }

# Ktor Server
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }

# Dependency Injection - Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

# Database
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Multiplatform Helpers
multiplatformSettings = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

# Desktop Specific
composenativetray = { module = "io.github.kdroidfilter:composenativetray", version.ref = "composenativetray" }
tulskiy-jkeymaster = { module = "com.github.tulskiy:jkeymaster", version.ref = "jkeymasterVersion" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jnativehook = { module = "com.github.kwhat:jnativehook", version.ref = "jnativehook" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }

# Navigation
androidx-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "compose-multiplatform-lifecycle" }


[plugins]
# Build & Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

# Kotlin
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Compose
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-hot-reload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
kobweb-application = { id = "com.varabyte.kobweb.application", version.ref = "kobweb" }

# Database
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }
